# Generated by Django 3.1.6 on 2021-02-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theportapp', '0003_remove_comment_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
