# Generated by Django 3.1.6 on 2021-02-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theportapp', '0005_auto_20210221_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
